//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TurfManagementDBEntities : DbContext
    {
        public TurfManagementDBEntities()
            : base("name=TurfManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Time_Slote> Time_Slote { get; set; }
        public virtual DbSet<Turf_Category> Turf_Category { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Turf> Turfs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spBookingDetailsWithSOmeConditions_Result> spBookingDetailsWithSOmeConditions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBookingDetailsWithSOmeConditions_Result>("spBookingDetailsWithSOmeConditions");
        }
    
        public virtual ObjectResult<spSloteBookingDetails_Result> spSloteBookingDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSloteBookingDetails_Result>("spSloteBookingDetails");
        }
    
        public virtual int spTurfDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTurfDetails");
        }
    }
}
