//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turf()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Turf_ID { get; set; }
        public string Turf_Name { get; set; }
        public string Turf_Location { get; set; }
        public int Opening_Time { get; set; }
        public int Closing_Time { get; set; }
        public int Turf_Category_ID { get; set; }
        public double Turf_Price { get; set; }
        public string Turf_City { get; set; }
        public string Turf_State { get; set; }
        public string Turf_Zip { get; set; }
        public int Turf_Status { get; set; }
        public string Turf_Image { get; set; }
    
        public virtual Time_Slote Time_Slote { get; set; }
        public virtual Time_Slote Time_Slote1 { get; set; }
        public virtual Turf_Category Turf_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
